# 4.1

In [1]:
import pandas as pd
import numpy as np

In [2]:
with open('Day4_Input.txt') as f:
    input = f.read()
    f.close

In [3]:
input = input.split(',')
input = list(map(int, input))

In [9]:
#get the boards into an array of subarrays

#read in the text as string to keep the leading zeros
lines = pd.read_csv('Day4_Boards.txt', header=None, sep='\n\n', dtype= 'str', engine='python')
lines = lines[0].str.split(' +', expand=True) #split on one or more spaces
                                              #(some numbers were a single digit with a leading space)

#convert to an array of integers
arr = np.asarray(lines, dtype='int32')
arr = np.split(arr, 100) #split into subarrays
arr

[array([[57, 80, 91, 40, 12],
        [62, 36, 72,  0, 20],
        [55, 60, 25, 92, 96],
        [14,  2, 17, 18, 86],
        [ 1,  4, 90, 66, 38]]),
 array([[ 1, 25, 81, 16, 24],
        [33, 40, 86, 28, 96],
        [ 4, 97, 90, 32, 13],
        [50, 38, 35, 14, 56],
        [73, 42,  9, 36, 67]]),
 array([[46, 25, 28, 59, 88],
        [33, 48, 15,  0, 95],
        [16, 30, 24,  2, 71],
        [11, 81, 58, 70, 65],
        [37,  1, 26, 94, 75]]),
 array([[53, 56,  5, 72, 99],
        [46, 27, 23, 49,  4],
        [ 3, 93, 21, 65, 37],
        [35,  7, 50, 32, 24],
        [81, 78, 52, 54, 88]]),
 array([[76, 14, 58, 84, 17],
        [ 5, 89, 97, 57, 15],
        [19, 77, 35, 56, 93],
        [31, 71, 92,  2, 39],
        [10, 27, 91, 67, 47]]),
 array([[27, 95, 74, 40, 50],
        [49, 66, 37, 80, 75],
        [54, 70,  1, 16, 41],
        [11, 77, 61,  6, 89],
        [71, 45, 73, 23, 29]]),
 array([[87, 72, 85, 89, 18],
        [91, 56, 54, 14, 88],
        [84, 46, 35,  9, 69]

In [7]:
win = False
i=0

while win == False:
    entry = input[i]
    
    for j in range(100):
        arr[j] = np.where(arr[j]==entry, 0, arr[j])
        row_sum = arr[j].sum(axis=1)
        col_sum = arr[j].sum(axis=0)
        total = arr[j].sum() * entry
        if np.any(row_sum == 0):
            win = True
            break

        if np.any(col_sum == 0):
            win = True
            break
    i += 1
print(total)

55770


In [ ]:
arr[0]

In [ ]:
arr_test = np.where(arr[0]==17, 0, arr[0])
arr_test

In [ ]:
np.any(arr[0].sum(axis=1)==280) #checks to see if there is a sum equal to 280

In [ ]:
#find and replace entries
arr_test=np.where(arr[0]==17, 0, arr[0])
arr_test

In [13]:
np.delete(arr, 0, axis=0) #remove subarry from array

array([[[ 1, 25, 81, 16, 24],
        [33, 40, 86, 28, 96],
        [ 4, 97, 90, 32, 13],
        [50, 38, 35, 14, 56],
        [73, 42,  9, 36, 67]],

       [[46, 25, 28, 59, 88],
        [33, 48, 15,  0, 95],
        [16, 30, 24,  2, 71],
        [11, 81, 58, 70, 65],
        [37,  1, 26, 94, 75]],

       [[53, 56,  5, 72, 99],
        [46, 27, 23, 49,  4],
        [ 3, 93, 21, 65, 37],
        [35,  7, 50, 32, 24],
        [81, 78, 52, 54, 88]],

       ...,

       [[26,  8, 64, 47, 76],
        [27, 15, 82, 65, 80],
        [54, 79, 84, 87, 37],
        [97, 18,  3, 93, 20],
        [88,  7, 40, 99, 35]],

       [[40, 94,  6, 53, 58],
        [45, 60, 81, 64, 30],
        [66, 55, 74, 37,  7],
        [63, 95, 23, 72, 17],
        [80, 18, 69, 89, 28]],

       [[48, 83, 84, 85,  3],
        [98, 80, 50, 96, 91],
        [18, 69, 44, 62, 15],
        [20, 88, 12, 45, 28],
        [ 8, 29,  0, 37, 27]]])

In [14]:
arr

[array([[57, 80, 91, 40, 12],
        [62, 36, 72,  0, 20],
        [55, 60, 25, 92, 96],
        [14,  2, 17, 18, 86],
        [ 1,  4, 90, 66, 38]]),
 array([[ 1, 25, 81, 16, 24],
        [33, 40, 86, 28, 96],
        [ 4, 97, 90, 32, 13],
        [50, 38, 35, 14, 56],
        [73, 42,  9, 36, 67]]),
 array([[46, 25, 28, 59, 88],
        [33, 48, 15,  0, 95],
        [16, 30, 24,  2, 71],
        [11, 81, 58, 70, 65],
        [37,  1, 26, 94, 75]]),
 array([[53, 56,  5, 72, 99],
        [46, 27, 23, 49,  4],
        [ 3, 93, 21, 65, 37],
        [35,  7, 50, 32, 24],
        [81, 78, 52, 54, 88]]),
 array([[76, 14, 58, 84, 17],
        [ 5, 89, 97, 57, 15],
        [19, 77, 35, 56, 93],
        [31, 71, 92,  2, 39],
        [10, 27, 91, 67, 47]]),
 array([[27, 95, 74, 40, 50],
        [49, 66, 37, 80, 75],
        [54, 70,  1, 16, 41],
        [11, 77, 61,  6, 89],
        [71, 45, 73, 23, 29]]),
 array([[87, 72, 85, 89, 18],
        [91, 56, 54, 14, 88],
        [84, 46, 35,  9, 69]