# 4.1 Find the Board that Wins First

In [1]:
#import packages
import pandas as pd
import numpy as np

In [2]:
#read the input
with open('Day4_Input.txt') as f:
    input = f.read()
    f.close

In [3]:
#split into list and convert to numbers
input = input.split(',')
input = list(map(int, input))

In [4]:
input #take a look

[17,
 11,
 37,
 7,
 89,
 48,
 99,
 28,
 56,
 55,
 57,
 27,
 83,
 59,
 53,
 72,
 6,
 87,
 33,
 82,
 13,
 23,
 35,
 40,
 71,
 47,
 78,
 2,
 39,
 4,
 51,
 1,
 67,
 31,
 79,
 69,
 15,
 73,
 80,
 22,
 92,
 95,
 91,
 43,
 26,
 97,
 36,
 34,
 12,
 96,
 86,
 52,
 66,
 94,
 61,
 76,
 64,
 77,
 85,
 98,
 42,
 68,
 84,
 63,
 60,
 30,
 65,
 19,
 54,
 58,
 24,
 20,
 25,
 75,
 93,
 16,
 18,
 44,
 14,
 88,
 45,
 10,
 9,
 3,
 70,
 74,
 81,
 90,
 46,
 38,
 21,
 49,
 29,
 50,
 0,
 5,
 8,
 32,
 62,
 41]

In [28]:
#get the boards into an array of subarrays

#read in the text as string to keep the leading zeros
lines = pd.read_csv('Day4_Boards.txt', header=None, sep='\n\n', dtype= 'str', engine='python')
lines = lines[0].str.split(' +', expand=True) #split on one or more spaces
                                              #(some numbers were a single digit with a leading space)

#convert to an array of integers
arr = np.asarray(lines, dtype='int32')
arr = np.split(arr, 100) #split into subarrays
arr

[array([[57, 80, 91, 40, 12],
        [62, 36, 72,  0, 20],
        [55, 60, 25, 92, 96],
        [14,  2, 17, 18, 86],
        [ 1,  4, 90, 66, 38]]),
 array([[ 1, 25, 81, 16, 24],
        [33, 40, 86, 28, 96],
        [ 4, 97, 90, 32, 13],
        [50, 38, 35, 14, 56],
        [73, 42,  9, 36, 67]]),
 array([[46, 25, 28, 59, 88],
        [33, 48, 15,  0, 95],
        [16, 30, 24,  2, 71],
        [11, 81, 58, 70, 65],
        [37,  1, 26, 94, 75]]),
 array([[53, 56,  5, 72, 99],
        [46, 27, 23, 49,  4],
        [ 3, 93, 21, 65, 37],
        [35,  7, 50, 32, 24],
        [81, 78, 52, 54, 88]]),
 array([[76, 14, 58, 84, 17],
        [ 5, 89, 97, 57, 15],
        [19, 77, 35, 56, 93],
        [31, 71, 92,  2, 39],
        [10, 27, 91, 67, 47]]),
 array([[27, 95, 74, 40, 50],
        [49, 66, 37, 80, 75],
        [54, 70,  1, 16, 41],
        [11, 77, 61,  6, 89],
        [71, 45, 73, 23, 29]]),
 array([[87, 72, 85, 89, 18],
        [91, 56, 54, 14, 88],
        [84, 46, 35,  9, 69]

In [6]:
#loop to find first winner

arr_test = arr.copy() #copy the array

#set parameters
win = False
i=0

#run until there's a winner
while win == False:
    
    entry = input[i]
    
    
    for j in range(100):
        arr_test[j] = np.where(arr_test[j]==entry, 0, arr_test[j]) #if the drawn number is in a subarray, replace it with zero
        row_sum = arr_test[j].sum(axis=1) #calculate row sums
        col_sum = arr_test[j].sum(axis=0) #calculate column sums
        total = arr_test[j].sum() * entry #calculate the total if this ends the game
        
        #if a row or column sum is zero, the board has bingo; exit the loop
        if np.any(row_sum == 0):
            win = True
            break

        if np.any(col_sum == 0):
            win = True
            break
            
    #iterate through the entries        
    i += 1
    
print(total)

55770


# 4.2 Find the Board the Wins Last

In [49]:
#copy the array
arr_test = arr.copy()

#initiate parameters including a list to capture indicies of boards that have won
arg = []
last = False
end = False
i=0

#lopo through until the last board wins
while end == False:

    #keep finding winning boards until only one board is left
    while len(arg) < 99:
        
        entry = input[i]
        print("This is entry: ", entry)
        for j in range(100):
            
            #ignor the board if it has already won
            if j in arg:
                continue
            
            #as in 4.1, but we will add the idex to arg if a board wins
            arr_test[j] = np.where(arr_test[j]==entry, 0, arr_test[j])
            row_sum = arr_test[j].sum(axis=1)
            col_sum = arr_test[j].sum(axis=0)
            total = arr_test[j].sum() * entry
            if np.any(row_sum == 0) or np.any(col_sum == 0):
                arg.append(j)
                print('Adding index: ', j)
                print('The length is now: ', len(arg))
                print(arr_test[j])
            

        i += 1
    
    #once all but the last board have won, we work only on that board
    last = True
    
    #see what the index of the final board is
    last_idx = [x for x in range(100) if x not in arg]
    print('The last index is: ', last_idx)

    #work through the draws until the last board wins
    if last == True:
        entry = input[i]
        print(entry)
        print(arr_test[last_idx[0]])
        arr_test[last_idx[0]] = np.where(arr_test[last_idx[0]]==entry, 0, arr_test[last_idx[0]])
        row_sum = arr_test[last_idx[0]].sum(axis=1)
        print(row_sum)
        col_sum = arr_test[last_idx[0]].sum(axis=0)
        print(col_sum)
        total = arr_test[last_idx[0]].sum() * entry
        print(total)
        if np.any(row_sum == 0):
            end = True
            last = False
        if np.any(col_sum == 0):
            end = True
            last = False
        print(arr_test[last_idx[0]])
        
        i += 1

#print total
print(total)


#it's not working, so this is for diagnostics
arg.sort()
print(arg)
print(last_idx[0])
for j in range(100):
    print(arr_test[j])

This is entry:  17
This is entry:  11
This is entry:  37
This is entry:  7
This is entry:  89
This is entry:  48
This is entry:  99
This is entry:  28
This is entry:  56
This is entry:  55
This is entry:  57
This is entry:  27
This is entry:  83
This is entry:  59
This is entry:  53
This is entry:  72
This is entry:  6
This is entry:  87
This is entry:  33
This is entry:  82
This is entry:  13
This is entry:  23
This is entry:  35
This is entry:  40
This is entry:  71
This is entry:  47
This is entry:  78
Adding index:  75
The length is now:  1
[[16 62  3 75 84]
 [54 10  1  2 44]
 [21 42  0  0 64]
 [91 45 67 34  0]
 [ 0  0  0  0  0]]
This is entry:  2
Adding index:  82
The length is now:  2
[[34 86 21  0  0]
 [ 0 20 39  0 66]
 [10  0 98  0  3]
 [ 0  0  0  0 70]
 [ 0 24 38  0 58]]
This is entry:  39
Adding index:  46
The length is now:  3
[[ 0  0  0  0  0]
 [96  0 67  0  0]
 [65 75  0 69  0]
 [16 15 86  0 85]
 [58 46  0 32  9]]
This is entry:  4
Adding index:  49
The length is now:  4
[